[project]
name = "web-apo"
version = "0.1.0"
description = "A standard FastAPI project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "mypy",
    "ruff",
]

[build-system]
requires = ["setuptools>=1.00"]
build-backend = "setuptools.build_meta"
